@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title V8引擎系统上下文图

Person(developer, "开发者", "编写JavaScript代码")
System(v8, "V8引擎", "Google的高性能JavaScript引擎")
System(chrome, "Chrome浏览器", "V8的主要宿主环境")
System(nodejs, "Node.js", "V8的服务器端运行时")

Rel(developer, v8, "编写JS代码")
Rel(chrome, v8, "嵌入执行")
Rel(nodejs, v8, "嵌入执行")

legend right
<b>关键关系</b>
1. V8是JavaScript的执行引擎
2. 被Chrome和Node.js等环境嵌入使用
endlegend

@enduml
